#! /bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          nordlayerd
# Required-Start:    mountkernfs $local_fs
# Required-Stop:
# Should-Start:      udev module-init-tools
# X-Start-Before:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configure nordlayer daemon
# Description:  Configure Nordlayer daemon
### END INIT INFO
#
# written by Berty Pribilovics <berty@ppcapinc.com>

DESC="NordLayer Daemon"
DAEMON=/usr/sbin/nordlayerd
PIDFILE=none

do_start_cmd() {
	STATUS=0
    nohup $DAEMON -config /etc/nordlayer/config.hcl > /var/log/nordlayer.log &
	return $STATUS
}

do_stop() {
    rm /run/nordlayer/nordlayer.sock
    return 0;
}
do_status() { return 0; }